package com.japanesedrills.ui.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.material3.Shapes
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

// Latte: cream page, white cards, an espresso question card and one caramel accent.
// Every value below is generated by tools/theme/schemes.py, which holds the reasoning
// and the alternatives that were considered; change a colour there and re-run --apply,
// not here, or the next run silently reverts you.

private val LightColors = lightColorScheme(
    primary = Color(0xFF904C1D),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF33241C),
    onPrimaryContainer = Color(0xFFF7EDE3),
    secondary = Color(0xFF904C1D),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFF0E0CF),
    onSecondaryContainer = Color(0xFF3A2616),
    tertiary = Color(0xFF904C1D),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFF0E0CF),
    onTertiaryContainer = Color(0xFF3A2616),
    error = Color(0xFF9C3B2E),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFBD9D0),
    onErrorContainer = Color(0xFF40120B),
    background = Color(0xFFFCF7F1),
    onBackground = Color(0xFF2B1D16),
    surface = Color(0xFFFCF7F1),
    onSurface = Color(0xFF2B1D16),
    surfaceVariant = Color(0xFFEFE2D5),
    onSurfaceVariant = Color(0xFF5A483C),
    outline = Color(0xFF8D7767),
    outlineVariant = Color(0xFFDECBB9),
    inverseSurface = Color(0xFF33241C),
    inverseOnSurface = Color(0xFFF7EDE3),
    inversePrimary = Color(0xFF904C1D),
    surfaceBright = Color(0xFFFCF7F1),
    surfaceDim = Color(0xFFEDE0D2),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFFFFFF),
    surfaceContainer = Color(0xFFF8EFE6),
    surfaceContainerHigh = Color(0xFFF3E8DC),
    surfaceContainerHighest = Color(0xFFEDE0D2),
)

private val DarkColors = darkColorScheme(
    primary = Color(0xFFF0A868),
    onPrimary = Color(0xFF4A2708),
    primaryContainer = Color(0xFF120D09),
    onPrimaryContainer = Color(0xFFF7EDE3),
    secondary = Color(0xFFF0A868),
    onSecondary = Color(0xFF4A2708),
    secondaryContainer = Color(0xFF3E2E22),
    onSecondaryContainer = Color(0xFFF1DFCD),
    tertiary = Color(0xFFF0A868),
    onTertiary = Color(0xFF4A2708),
    tertiaryContainer = Color(0xFF3E2E22),
    onTertiaryContainer = Color(0xFFF1DFCD),
    error = Color(0xFFFFB4A2),
    onError = Color(0xFF5C1A0F),
    errorContainer = Color(0xFF7A2E20),
    onErrorContainer = Color(0xFFFFDAD2),
    background = Color(0xFF1C1511),
    onBackground = Color(0xFFEFE3D9),
    surface = Color(0xFF1C1511),
    onSurface = Color(0xFFEFE3D9),
    surfaceVariant = Color(0xFF4E3D31),
    onSurfaceVariant = Color(0xFFD6C3B4),
    outline = Color(0xFF9E8878),
    outlineVariant = Color(0xFF4E3D31),
    inverseSurface = Color(0xFFEFE3D9),
    inverseOnSurface = Color(0xFF2B1D16),
    inversePrimary = Color(0xFFF0A868),
    surfaceBright = Color(0xFF1C1511),
    surfaceDim = Color(0xFF3F332A),
    surfaceContainerLowest = Color(0xFF231A15),
    surfaceContainerLow = Color(0xFF231A15),
    surfaceContainer = Color(0xFF27201A),
    surfaceContainerHigh = Color(0xFF332921),
    surfaceContainerHighest = Color(0xFF3F332A),
)

/** Colours for right answers, which Material 3 has no role for. Wrong answers use the error roles. */
@Immutable
data class AnswerColors(
    val correct: Color,
    val onCorrect: Color,
    val correctContainer: Color,
    val onCorrectContainer: Color,
)

private val LightAnswerColors = AnswerColors(
    correct = Color(0xFF3F6B2B),
    onCorrect = Color(0xFFFFFFFF),
    correctContainer = Color(0xFFD2EAC0),
    onCorrectContainer = Color(0xFF14260A),
)

private val DarkAnswerColors = AnswerColors(
    correct = Color(0xFFA8CF8C),
    onCorrect = Color(0xFF1E3410),
    correctContainer = Color(0xFF374E26),
    onCorrectContainer = Color(0xFFD2EAC0),
)

/** Softer than Material's defaults: a warm room has no sharp corners. */
private val AppShapes = Shapes(
    extraLarge = RoundedCornerShape(28.dp),
    large = RoundedCornerShape(22.dp),
    medium = RoundedCornerShape(18.dp),
    small = RoundedCornerShape(12.dp),
)

private val LocalAnswerColors = staticCompositionLocalOf { LightAnswerColors }

object DrillTheme {
    val answerColors: AnswerColors
        @Composable get() = LocalAnswerColors.current
}

@Composable
fun JapaneseDrillsTheme(darkTheme: Boolean = isSystemInDarkTheme(), content: @Composable () -> Unit) {
    CompositionLocalProvider(LocalAnswerColors provides if (darkTheme) DarkAnswerColors else LightAnswerColors) {
        MaterialTheme(
            colorScheme = if (darkTheme) DarkColors else LightColors,
            typography = AppTypography,
            shapes = AppShapes,
            content = content,
        )
    }
}
