package com.japanesedrills.ui.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.ColorScheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Shapes
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.remember
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.lerp
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import com.japanesedrills.R
import com.japanesedrills.quiz.Palette

// The palettes Settings offers. Each is a colour scheme for both modes, a pair of typefaces
// and a decision about where the accent goes. Everything between the generated markers
// comes from tools/theme/schemes.py, which holds the reasoning behind each palette; change
// one there and re-run --apply, not here, or the next run silently reverts you.

/** Colours for right answers, which Material 3 has no role for. Wrong answers use the error roles. */
@Immutable
data class AnswerColors(
    val correct: Color,
    val onCorrect: Color,
    val correctContainer: Color,
    val onCorrectContainer: Color,
)

/**
 * Colours for what the Conjugation Intro's worked examples mark: the last kana, the form's
 * ending, and the two fused. Each is also set apart by weight or underline, so none rests on colour alone.
 */
@Immutable
data class MarkColors(
    val markKana: Color,
    val markEnding: Color,
    val markFused: Color,
)

/**
 * How well something is holding up in review, as a bar fills: clay while it is barely
 * started, ochre in the middle, green when it is solid. Off the accent on purpose, so a full
 * bar reads as a measurement rather than as something to tap.
 */
@Immutable
data class StrengthColors(
    val strengthLow: Color,
    val strengthMid: Color,
    val strengthHigh: Color,
) {
    /** The colour a bar [filled] 0f..1f is drawn in, mixed across the ramp. */
    fun at(filled: Float): Color {
        val level = filled.coerceIn(0f, 1f)
        return if (level < 0.5f) {
            lerp(strengthLow, strengthMid, level * 2f)
        } else {
            lerp(strengthMid, strengthHigh, (level - 0.5f) * 2f)
        }
    }
}

/**
 * Where a palette spends its accent beyond the roles every palette shares: on section
 * titles, and on the word-class headings in the grammar reference. It is what makes the
 * palettes different answers rather than one layout recoloured.
 */
@Immutable
data class Accents(val titles: Boolean, val headings: Boolean)

/** One palette: colours for each mode, its two faces, and where its accent goes. */
class PaletteSpec(
    val light: ColorScheme,
    val dark: ColorScheme,
    val lightAnswers: AnswerColors,
    val darkAnswers: AnswerColors,
    val lightStrength: StrengthColors,
    val darkStrength: StrengthColors,
    val lightMarks: MarkColors,
    val darkMarks: MarkColors,
    val display: FontFamily,
    val body: FontFamily,
    /** The two faces by name, for the theme picker. */
    val faces: String,
    val accents: Accents,
)

// <generated by tools/theme/schemes.py --apply>
private val LoraFace = face(
    R.font.lora_regular,
    R.font.lora_medium,
    R.font.lora_semibold,
    R.font.lora_bold,
)
private val ManropeFace = face(
    R.font.manrope_regular,
    R.font.manrope_medium,
    R.font.manrope_semibold,
    R.font.manrope_bold,
)
private val OutfitFace = face(
    R.font.outfit_regular,
    R.font.outfit_medium,
    R.font.outfit_semibold,
    R.font.outfit_bold,
)
private val FrauncesFace = face(
    R.font.fraunces_regular,
    R.font.fraunces_medium,
    R.font.fraunces_semibold,
    R.font.fraunces_bold,
)
private val NunitosansFace = face(
    R.font.nunitosans_regular,
    R.font.nunitosans_medium,
    R.font.nunitosans_semibold,
    R.font.nunitosans_bold,
)

private val LatteSpec = PaletteSpec(
    light = lightColorScheme(
        primary = Color(0xFF904C1D),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFEBDCCF),
        onPrimaryContainer = Color(0xFF2B1D16),
        secondary = Color(0xFF904C1D),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFF0E0CF),
        onSecondaryContainer = Color(0xFF3A2616),
        tertiary = Color(0xFF904C1D),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFF0E0CF),
        onTertiaryContainer = Color(0xFF3A2616),
        error = Color(0xFF9C3B2E),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFBD9D0),
        onErrorContainer = Color(0xFF40120B),
        background = Color(0xFFFCF7F1),
        onBackground = Color(0xFF2B1D16),
        surface = Color(0xFFFCF7F1),
        onSurface = Color(0xFF2B1D16),
        surfaceVariant = Color(0xFFEFE2D5),
        onSurfaceVariant = Color(0xFF544337),
        outline = Color(0xFF867162),
        outlineVariant = Color(0xFFDECBB9),
        inverseSurface = Color(0xFF33241C),
        inverseOnSurface = Color(0xFFF7EDE3),
        inversePrimary = Color(0xFF904C1D),
        surfaceBright = Color(0xFFFCF7F1),
        surfaceDim = Color(0xFFEDE0D2),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFFFFFF),
        surfaceContainer = Color(0xFFF8EFE6),
        surfaceContainerHigh = Color(0xFFF3E8DC),
        surfaceContainerHighest = Color(0xFFEDE0D2),
    ),
    dark = darkColorScheme(
        primary = Color(0xFFF0A868),
        onPrimary = Color(0xFF4A2708),
        primaryContainer = Color(0xFF3E2D1F),
        onPrimaryContainer = Color(0xFFEFE3D9),
        secondary = Color(0xFFF0A868),
        onSecondary = Color(0xFF4A2708),
        secondaryContainer = Color(0xFF3E2E22),
        onSecondaryContainer = Color(0xFFF1DFCD),
        tertiary = Color(0xFFF0A868),
        onTertiary = Color(0xFF4A2708),
        tertiaryContainer = Color(0xFF3E2E22),
        onTertiaryContainer = Color(0xFFF1DFCD),
        error = Color(0xFFFFB4A2),
        onError = Color(0xFF5C1A0F),
        errorContainer = Color(0xFF7A2E20),
        onErrorContainer = Color(0xFFFFDAD2),
        background = Color(0xFF1C1511),
        onBackground = Color(0xFFEFE3D9),
        surface = Color(0xFF1C1511),
        onSurface = Color(0xFFEFE3D9),
        surfaceVariant = Color(0xFF4E3D31),
        onSurfaceVariant = Color(0xFFD6C3B4),
        outline = Color(0xFF9E8878),
        outlineVariant = Color(0xFF4E3D31),
        inverseSurface = Color(0xFFEFE3D9),
        inverseOnSurface = Color(0xFF2B1D16),
        inversePrimary = Color(0xFFF0A868),
        surfaceBright = Color(0xFF1C1511),
        surfaceDim = Color(0xFF3F332A),
        surfaceContainerLowest = Color(0xFF231A15),
        surfaceContainerLow = Color(0xFF231A15),
        surfaceContainer = Color(0xFF27201A),
        surfaceContainerHigh = Color(0xFF332921),
        surfaceContainerHighest = Color(0xFF3F332A),
    ),
    lightAnswers = AnswerColors(
        correct = Color(0xFF3F6B2B),
        onCorrect = Color(0xFFFFFFFF),
        correctContainer = Color(0xFFD2EAC0),
        onCorrectContainer = Color(0xFF14260A),
    ),
    darkAnswers = AnswerColors(
        correct = Color(0xFFA8CF8C),
        onCorrect = Color(0xFF1E3410),
        correctContainer = Color(0xFF374E26),
        onCorrectContainer = Color(0xFFD2EAC0),
    ),
    lightMarks = MarkColors(
        markKana = Color(0xFF904C1D),
        markEnding = Color(0xFF1F5C8F),
        markFused = Color(0xFF7B3A82),
    ),
    darkMarks = MarkColors(
        markKana = Color(0xFFF0A868),
        markEnding = Color(0xFF8FC2F0),
        markFused = Color(0xFFE2A6E6),
    ),
    lightStrength = StrengthColors(
        strengthLow = Color(0xFF993A22),
        strengthMid = Color(0xFF6F4A07),
        strengthHigh = Color(0xFF255A2B),
    ),
    darkStrength = StrengthColors(
        strengthLow = Color(0xFFE79C7C),
        strengthMid = Color(0xFFDBB868),
        strengthHigh = Color(0xFF97CA94),
    ),
    display = LoraFace,
    body = ManropeFace,
    faces = "Lora · Manrope",
    accents = Accents(titles = false, headings = true),
)

private val KissatenSpec = PaletteSpec(
    light = lightColorScheme(
        primary = Color(0xFF8E4419),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFE4D2C4),
        onPrimaryContainer = Color(0xFF241A14),
        secondary = Color(0xFF8E4419),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFE3D2BE),
        onSecondaryContainer = Color(0xFF2E2013),
        tertiary = Color(0xFF8E4419),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFE3D2BE),
        onTertiaryContainer = Color(0xFF2E2013),
        error = Color(0xFF96342A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFF6D3CB),
        onErrorContainer = Color(0xFF3A0F09),
        background = Color(0xFFF4EDE4),
        onBackground = Color(0xFF241A14),
        surface = Color(0xFFF4EDE4),
        onSurface = Color(0xFF241A14),
        surfaceVariant = Color(0xFFE3D6C5),
        onSurfaceVariant = Color(0xFF4B3D31),
        outline = Color(0xFF816C5B),
        outlineVariant = Color(0xFFCDBCA6),
        inverseSurface = Color(0xFF241A14),
        inverseOnSurface = Color(0xFFF2E6D8),
        inversePrimary = Color(0xFF8E4419),
        surfaceBright = Color(0xFFF4EDE4),
        surfaceDim = Color(0xFFE2D5C4),
        surfaceContainerLowest = Color(0xFFFBF6EE),
        surfaceContainerLow = Color(0xFFFBF6EE),
        surfaceContainer = Color(0xFFEFE6DA),
        surfaceContainerHigh = Color(0xFFE9DED0),
        surfaceContainerHighest = Color(0xFFE2D5C4),
    ),
    dark = darkColorScheme(
        primary = Color(0xFFE89B62),
        onPrimary = Color(0xFF44220A),
        primaryContainer = Color(0xFF3A291D),
        onPrimaryContainer = Color(0xFFEADFD3),
        secondary = Color(0xFFE89B62),
        onSecondary = Color(0xFF44220A),
        secondaryContainer = Color(0xFF3A2C1E),
        onSecondaryContainer = Color(0xFFE8D8C4),
        tertiary = Color(0xFFE89B62),
        onTertiary = Color(0xFF44220A),
        tertiaryContainer = Color(0xFF3A2C1E),
        onTertiaryContainer = Color(0xFFE8D8C4),
        error = Color(0xFFFFB3A1),
        onError = Color(0xFF57180E),
        errorContainer = Color(0xFF752B1E),
        onErrorContainer = Color(0xFFFFDAD2),
        background = Color(0xFF191310),
        onBackground = Color(0xFFEADFD3),
        surface = Color(0xFF191310),
        onSurface = Color(0xFFEADFD3),
        surfaceVariant = Color(0xFF4A3B2D),
        onSurfaceVariant = Color(0xFFD2C1AE),
        outline = Color(0xFF9A8571),
        outlineVariant = Color(0xFF4A3B2D),
        inverseSurface = Color(0xFFEADFD3),
        inverseOnSurface = Color(0xFF241A14),
        inversePrimary = Color(0xFFE89B62),
        surfaceBright = Color(0xFF191310),
        surfaceDim = Color(0xFF3D3128),
        surfaceContainerLowest = Color(0xFF201813),
        surfaceContainerLow = Color(0xFF201813),
        surfaceContainer = Color(0xFF251D17),
        surfaceContainerHigh = Color(0xFF31271F),
        surfaceContainerHighest = Color(0xFF3D3128),
    ),
    lightAnswers = AnswerColors(
        correct = Color(0xFF3C6630),
        onCorrect = Color(0xFFFFFFFF),
        correctContainer = Color(0xFFCDE6BE),
        onCorrectContainer = Color(0xFF12250B),
    ),
    darkAnswers = AnswerColors(
        correct = Color(0xFFA4CB88),
        onCorrect = Color(0xFF1B300F),
        correctContainer = Color(0xFF344A24),
        onCorrectContainer = Color(0xFFCDE6BE),
    ),
    lightMarks = MarkColors(
        markKana = Color(0xFF8E4419),
        markEnding = Color(0xFF1F5C8F),
        markFused = Color(0xFF7B3A82),
    ),
    darkMarks = MarkColors(
        markKana = Color(0xFFE89B62),
        markEnding = Color(0xFF8FC2F0),
        markFused = Color(0xFFE2A6E6),
    ),
    lightStrength = StrengthColors(
        strengthLow = Color(0xFF993A22),
        strengthMid = Color(0xFF6F4A07),
        strengthHigh = Color(0xFF255A2B),
    ),
    darkStrength = StrengthColors(
        strengthLow = Color(0xFFE79C7C),
        strengthMid = Color(0xFFDBB868),
        strengthHigh = Color(0xFF97CA94),
    ),
    display = LoraFace,
    body = ManropeFace,
    faces = "Lora · Manrope",
    accents = Accents(titles = true, headings = true),
)

private val WashiSpec = PaletteSpec(
    light = lightColorScheme(
        primary = Color(0xFFA34422),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFEAD7CC),
        onPrimaryContainer = Color(0xFF241C17),
        secondary = Color(0xFFA34422),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFF2EBE2),
        onSecondaryContainer = Color(0xFF241C17),
        tertiary = Color(0xFFA34422),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFF2EBE2),
        onTertiaryContainer = Color(0xFF241C17),
        error = Color(0xFFA03225),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFAD6CD),
        onErrorContainer = Color(0xFF3B0E07),
        background = Color(0xFFF7F3EC),
        onBackground = Color(0xFF241C17),
        surface = Color(0xFFF7F3EC),
        onSurface = Color(0xFF241C17),
        surfaceVariant = Color(0xFFEAE3D8),
        onSurfaceVariant = Color(0xFF4C423A),
        outline = Color(0xFF7F7365),
        outlineVariant = Color(0xFFD9D0C3),
        inverseSurface = Color(0xFF2E2620),
        inverseOnSurface = Color(0xFFF7F3EC),
        inversePrimary = Color(0xFFA34422),
        surfaceBright = Color(0xFFF7F3EC),
        surfaceDim = Color(0xFFEBE5DB),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFFFFFF),
        surfaceContainer = Color(0xFFFCF9F4),
        surfaceContainerHigh = Color(0xFFF2EDE5),
        surfaceContainerHighest = Color(0xFFEBE5DB),
    ),
    dark = darkColorScheme(
        primary = Color(0xFFFF9E72),
        onPrimary = Color(0xFF54200B),
        primaryContainer = Color(0xFF3A2820),
        onPrimaryContainer = Color(0xFFEFE6DC),
        secondary = Color(0xFFFF9E72),
        onSecondary = Color(0xFF54200B),
        secondaryContainer = Color(0xFF332C26),
        onSecondaryContainer = Color(0xFFEFE6DC),
        tertiary = Color(0xFFFF9E72),
        onTertiary = Color(0xFF54200B),
        tertiaryContainer = Color(0xFF332C26),
        onTertiaryContainer = Color(0xFFEFE6DC),
        error = Color(0xFFFFB4A0),
        onError = Color(0xFF5C1A0D),
        errorContainer = Color(0xFF7A2C1C),
        onErrorContainer = Color(0xFFFFDAD2),
        background = Color(0xFF151210),
        onBackground = Color(0xFFEFE6DC),
        surface = Color(0xFF151210),
        onSurface = Color(0xFFEFE6DC),
        surfaceVariant = Color(0xFF463E36),
        onSurfaceVariant = Color(0xFFCBC1B5),
        outline = Color(0xFF968B7E),
        outlineVariant = Color(0xFF463E36),
        inverseSurface = Color(0xFFEFE6DC),
        inverseOnSurface = Color(0xFF241C17),
        inversePrimary = Color(0xFFFF9E72),
        surfaceBright = Color(0xFF151210),
        surfaceDim = Color(0xFF362F29),
        surfaceContainerLowest = Color(0xFF1B1714),
        surfaceContainerLow = Color(0xFF1B1714),
        surfaceContainer = Color(0xFF201B18),
        surfaceContainerHigh = Color(0xFF2B2520),
        surfaceContainerHighest = Color(0xFF362F29),
    ),
    lightAnswers = AnswerColors(
        correct = Color(0xFF3E6A2A),
        onCorrect = Color(0xFFFFFFFF),
        correctContainer = Color(0xFFD6EDC6),
        onCorrectContainer = Color(0xFF132509),
    ),
    darkAnswers = AnswerColors(
        correct = Color(0xFFA9CE8E),
        onCorrect = Color(0xFF1D3311),
        correctContainer = Color(0xFF364C27),
        onCorrectContainer = Color(0xFFD6EDC6),
    ),
    lightMarks = MarkColors(
        markKana = Color(0xFFA34422),
        markEnding = Color(0xFF1F5C8F),
        markFused = Color(0xFF7B3A82),
    ),
    darkMarks = MarkColors(
        markKana = Color(0xFFFF9E72),
        markEnding = Color(0xFF8FC2F0),
        markFused = Color(0xFFE2A6E6),
    ),
    lightStrength = StrengthColors(
        strengthLow = Color(0xFF993A22),
        strengthMid = Color(0xFF6F4A07),
        strengthHigh = Color(0xFF255A2B),
    ),
    darkStrength = StrengthColors(
        strengthLow = Color(0xFFE79C7C),
        strengthMid = Color(0xFFDBB868),
        strengthHigh = Color(0xFF97CA94),
    ),
    display = OutfitFace,
    body = OutfitFace,
    faces = "Outfit",
    accents = Accents(titles = false, headings = false),
)

private val CaramelSpec = PaletteSpec(
    light = lightColorScheme(
        primary = Color(0xFF4A3021),
        onPrimary = Color(0xFFFFF6ED),
        primaryContainer = Color(0xFFE0D8D1),
        onPrimaryContainer = Color(0xFF2E2118),
        secondary = Color(0xFF4A3021),
        onSecondary = Color(0xFFFFF6ED),
        secondaryContainer = Color(0xFFF6E3CC),
        onSecondaryContainer = Color(0xFF3A2614),
        tertiary = Color(0xFF4A3021),
        onTertiary = Color(0xFFFFF6ED),
        tertiaryContainer = Color(0xFFF6E3CC),
        onTertiaryContainer = Color(0xFF3A2614),
        error = Color(0xFF9B3526),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFBD7CD),
        onErrorContainer = Color(0xFF3C0F07),
        background = Color(0xFFFDF8F2),
        onBackground = Color(0xFF2E2118),
        surface = Color(0xFFFDF8F2),
        onSurface = Color(0xFF2E2118),
        surfaceVariant = Color(0xFFEFE1D0),
        onSurfaceVariant = Color(0xFF504033),
        outline = Color(0xFF867260),
        outlineVariant = Color(0xFFDFCDB8),
        inverseSurface = Color(0xFF2E2118),
        inverseOnSurface = Color(0xFFFDF8F2),
        inversePrimary = Color(0xFF4A3021),
        surfaceBright = Color(0xFFFDF8F2),
        surfaceDim = Color(0xFFEEE1D0),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFFFFFF),
        surfaceContainer = Color(0xFFF9F0E5),
        surfaceContainerHigh = Color(0xFFF4E9DB),
        surfaceContainerHighest = Color(0xFFEEE1D0),
    ),
    dark = darkColorScheme(
        primary = Color(0xFFF4D0A6),
        onPrimary = Color(0xFF3A2513),
        primaryContainer = Color(0xFF3F3429),
        onPrimaryContainer = Color(0xFFF1E5D9),
        secondary = Color(0xFFF4D0A6),
        onSecondary = Color(0xFF3A2513),
        secondaryContainer = Color(0xFF40301F),
        onSecondaryContainer = Color(0xFFF3E1C9),
        tertiary = Color(0xFFF4D0A6),
        onTertiary = Color(0xFF3A2513),
        tertiaryContainer = Color(0xFF40301F),
        onTertiaryContainer = Color(0xFFF3E1C9),
        error = Color(0xFFFFB4A2),
        onError = Color(0xFF5C1A0F),
        errorContainer = Color(0xFF7A2E20),
        onErrorContainer = Color(0xFFFFDAD2),
        background = Color(0xFF1D1611),
        onBackground = Color(0xFFF1E5D9),
        surface = Color(0xFF1D1611),
        onSurface = Color(0xFFF1E5D9),
        surfaceVariant = Color(0xFF50402F),
        onSurfaceVariant = Color(0xFFD8C6B1),
        outline = Color(0xFFA08B74),
        outlineVariant = Color(0xFF50402F),
        inverseSurface = Color(0xFFF1E5D9),
        inverseOnSurface = Color(0xFF2E2118),
        inversePrimary = Color(0xFFF4D0A6),
        surfaceBright = Color(0xFF1D1611),
        surfaceDim = Color(0xFF41342A),
        surfaceContainerLowest = Color(0xFF241B15),
        surfaceContainerLow = Color(0xFF241B15),
        surfaceContainer = Color(0xFF29201A),
        surfaceContainerHigh = Color(0xFF352A21),
        surfaceContainerHighest = Color(0xFF41342A),
    ),
    lightAnswers = AnswerColors(
        correct = Color(0xFF3F6B2B),
        onCorrect = Color(0xFFFFFFFF),
        correctContainer = Color(0xFFD2EAC0),
        onCorrectContainer = Color(0xFF14260A),
    ),
    darkAnswers = AnswerColors(
        correct = Color(0xFFA8CF8C),
        onCorrect = Color(0xFF1E3410),
        correctContainer = Color(0xFF374E26),
        onCorrectContainer = Color(0xFFD2EAC0),
    ),
    lightMarks = MarkColors(
        markKana = Color(0xFF4A3021),
        markEnding = Color(0xFF1F5C8F),
        markFused = Color(0xFF7B3A82),
    ),
    darkMarks = MarkColors(
        markKana = Color(0xFFF4D0A6),
        markEnding = Color(0xFF8FC2F0),
        markFused = Color(0xFFE2A6E6),
    ),
    lightStrength = StrengthColors(
        strengthLow = Color(0xFF993A22),
        strengthMid = Color(0xFF6F4A07),
        strengthHigh = Color(0xFF255A2B),
    ),
    darkStrength = StrengthColors(
        strengthLow = Color(0xFFE79C7C),
        strengthMid = Color(0xFFDBB868),
        strengthHigh = Color(0xFF97CA94),
    ),
    display = FrauncesFace,
    body = NunitosansFace,
    faces = "Fraunces · Nunito Sans",
    accents = Accents(titles = false, headings = true),
)

private val MochaSpec = PaletteSpec(
    light = lightColorScheme(
        primary = Color(0xFF7E5213),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFE6DAC8),
        onPrimaryContainer = Color(0xFF271E14),
        secondary = Color(0xFF7E5213),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFEFE2CE),
        onSecondaryContainer = Color(0xFF2E2214),
        tertiary = Color(0xFF7E5213),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFEFE2CE),
        onTertiaryContainer = Color(0xFF2E2214),
        error = Color(0xFF98362A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFF8D6CD),
        onErrorContainer = Color(0xFF3A1009),
        background = Color(0xFFFAF4EA),
        onBackground = Color(0xFF271E14),
        surface = Color(0xFFFAF4EA),
        onSurface = Color(0xFF271E14),
        surfaceVariant = Color(0xFFEBE0CE),
        onSurfaceVariant = Color(0xFF4F4232),
        outline = Color(0xFF7F715D),
        outlineVariant = Color(0xFFD4C6AE),
        inverseSurface = Color(0xFF271E14),
        inverseOnSurface = Color(0xFFFAF4EA),
        inversePrimary = Color(0xFF7E5213),
        surfaceBright = Color(0xFFFAF4EA),
        surfaceDim = Color(0xFFE8DECE),
        surfaceContainerLowest = Color(0xFFFFFCF6),
        surfaceContainerLow = Color(0xFFFFFCF6),
        surfaceContainer = Color(0xFFF5EDE1),
        surfaceContainerHigh = Color(0xFFEFE6D8),
        surfaceContainerHighest = Color(0xFFE8DECE),
    ),
    dark = darkColorScheme(
        primary = Color(0xFFF0B75E),
        onPrimary = Color(0xFF412C00),
        primaryContainer = Color(0xFF40311E),
        onPrimaryContainer = Color(0xFFF0E5D8),
        secondary = Color(0xFFF0B75E),
        onSecondary = Color(0xFF412C00),
        secondaryContainer = Color(0xFF40342A),
        onSecondaryContainer = Color(0xFFEFE0CE),
        tertiary = Color(0xFFF0B75E),
        onTertiary = Color(0xFF412C00),
        tertiaryContainer = Color(0xFF40342A),
        onTertiaryContainer = Color(0xFFEFE0CE),
        error = Color(0xFFFFB4A2),
        onError = Color(0xFF5C1A0F),
        errorContainer = Color(0xFF7E3020),
        onErrorContainer = Color(0xFFFFDAD2),
        background = Color(0xFF1F1712),
        onBackground = Color(0xFFF0E5D8),
        surface = Color(0xFF1F1712),
        onSurface = Color(0xFFF0E5D8),
        surfaceVariant = Color(0xFF51433A),
        onSurfaceVariant = Color(0xFFD7C7B6),
        outline = Color(0xFF9F8C79),
        outlineVariant = Color(0xFF51433A),
        inverseSurface = Color(0xFFF0E5D8),
        inverseOnSurface = Color(0xFF271E14),
        inversePrimary = Color(0xFFF0B75E),
        surfaceBright = Color(0xFF1F1712),
        surfaceDim = Color(0xFF44362C),
        surfaceContainerLowest = Color(0xFF261D17),
        surfaceContainerLow = Color(0xFF261D17),
        surfaceContainer = Color(0xFF2C221B),
        surfaceContainerHigh = Color(0xFF382C24),
        surfaceContainerHighest = Color(0xFF44362C),
    ),
    lightAnswers = AnswerColors(
        correct = Color(0xFF3F6B2B),
        onCorrect = Color(0xFFFFFFFF),
        correctContainer = Color(0xFFD2EAC0),
        onCorrectContainer = Color(0xFF14260A),
    ),
    darkAnswers = AnswerColors(
        correct = Color(0xFFA8CF8C),
        onCorrect = Color(0xFF1E3410),
        correctContainer = Color(0xFF374E26),
        onCorrectContainer = Color(0xFFD2EAC0),
    ),
    lightMarks = MarkColors(
        markKana = Color(0xFF7E5213),
        markEnding = Color(0xFF1F5C8F),
        markFused = Color(0xFF7B3A82),
    ),
    darkMarks = MarkColors(
        markKana = Color(0xFFF0B75E),
        markEnding = Color(0xFF8FC2F0),
        markFused = Color(0xFFE2A6E6),
    ),
    lightStrength = StrengthColors(
        strengthLow = Color(0xFF993A22),
        strengthMid = Color(0xFF6F4A07),
        strengthHigh = Color(0xFF255A2B),
    ),
    darkStrength = StrengthColors(
        strengthLow = Color(0xFFE79C7C),
        strengthMid = Color(0xFFDBB868),
        strengthHigh = Color(0xFF97CA94),
    ),
    display = ManropeFace,
    body = ManropeFace,
    faces = "Manrope",
    accents = Accents(titles = true, headings = true),
)

private fun specOf(palette: Palette): PaletteSpec = when (palette) {
    Palette.Latte -> LatteSpec
    Palette.Kissaten -> KissatenSpec
    Palette.Washi -> WashiSpec
    Palette.Caramel -> CaramelSpec
    Palette.Mocha -> MochaSpec
}
// </generated>

/**
 * Tight corners, the same for every palette: a card reads as a panel rather than a pill.
 * Anything meant to be round asks for a circle outright rather than relying on these.
 */
private val AppShapes = Shapes(
    extraSmall = RoundedCornerShape(4.dp),
    small = RoundedCornerShape(6.dp),
    medium = RoundedCornerShape(8.dp),
    large = RoundedCornerShape(10.dp),
    extraLarge = RoundedCornerShape(12.dp),
)

private val LocalAnswerColors = staticCompositionLocalOf { specOf(Palette.Latte).lightAnswers }
private val LocalMarkColors = staticCompositionLocalOf { specOf(Palette.Latte).lightMarks }
private val LocalStrengthColors = staticCompositionLocalOf { specOf(Palette.Latte).lightStrength }
private val LocalAccents = staticCompositionLocalOf { specOf(Palette.Latte).accents }

object DrillTheme {
    val answerColors: AnswerColors
        @Composable get() = LocalAnswerColors.current

    val markColors: MarkColors
        @Composable get() = LocalMarkColors.current

    val strengthColors: StrengthColors
        @Composable get() = LocalStrengthColors.current

    val accents: Accents
        @Composable get() = LocalAccents.current
}

/** The two faces [palette] is set in, by name. */
fun facesOf(palette: Palette): String = specOf(palette).faces

@Composable
fun JapaneseDrillsTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    palette: Palette = Palette.Latte,
    content: @Composable () -> Unit,
) {
    val spec = specOf(palette)
    val typography = remember(palette) { typographyOf(spec.display, spec.body) }
    CompositionLocalProvider(
        LocalAnswerColors provides if (darkTheme) spec.darkAnswers else spec.lightAnswers,
        LocalMarkColors provides if (darkTheme) spec.darkMarks else spec.lightMarks,
        LocalStrengthColors provides if (darkTheme) spec.darkStrength else spec.lightStrength,
        LocalAccents provides spec.accents,
    ) {
        MaterialTheme(
            colorScheme = if (darkTheme) spec.dark else spec.light,
            typography = typography,
            shapes = AppShapes,
            content = content,
        )
    }
}
